name = "OriDET Pack"
author = "Mangos_ & Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "174ec9c99b682f0c9195a0e5a879447835b5324a37518986bcec965c059b8d98"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.232"
