name = "OriDET Pack"
author = "Mangos_ & Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6ce07e9c1a11b5b7fb098cd623bcbd721bcafc17fdd327abbe5d53d1af45898"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.232"
