name = "OriDET Pack"
author = "Mangos_ & Schoperation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd79bc8348b0b5bdbb6aa98f502c34b95f8c4812fd511f487fd731b8f5f3d5a3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.232"
